// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJd2kJwXt4uT4JLaa_JX_dJI5h3wA8g8',
    appId: '1:296678093681:web:4458109a1424505e263cd0',
    messagingSenderId: '296678093681',
    projectId: 'lokasync',
    authDomain: 'lokasync.firebaseapp.com',
    storageBucket: 'lokasync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qkkE11sXZSnEWlfuxs96Cp2nwWp9Chk',
    appId: '1:296678093681:android:591bd0cbd1fc1e5b263cd0',
    messagingSenderId: '296678093681',
    projectId: 'lokasync',
    storageBucket: 'lokasync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1QoG-FrBBpnwmTrFWlR5IrLPaNYCfNVk',
    appId: '1:296678093681:ios:ba4b1024ae242906263cd0',
    messagingSenderId: '296678093681',
    projectId: 'lokasync',
    storageBucket: 'lokasync.firebasestorage.app',
    iosClientId: '296678093681-du9dc0jkcethbjgbnk125tmb8l8qmrde.apps.googleusercontent.com',
    iosBundleId: 'com.lokatani.lokasync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1QoG-FrBBpnwmTrFWlR5IrLPaNYCfNVk',
    appId: '1:296678093681:ios:ba4b1024ae242906263cd0',
    messagingSenderId: '296678093681',
    projectId: 'lokasync',
    storageBucket: 'lokasync.firebasestorage.app',
    iosClientId: '296678093681-du9dc0jkcethbjgbnk125tmb8l8qmrde.apps.googleusercontent.com',
    iosBundleId: 'com.lokatani.lokasync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmJd2kJwXt4uT4JLaa_JX_dJI5h3wA8g8',
    appId: '1:296678093681:web:53295b5475414bbb263cd0',
    messagingSenderId: '296678093681',
    projectId: 'lokasync',
    authDomain: 'lokasync.firebaseapp.com',
    storageBucket: 'lokasync.firebasestorage.app',
  );
}
